name = "JunoUtils"
uuid = "f0a8aab3-0b04-40fd-9cf1-346fd3100943"
authors = ["CarpeNecopinum <CarpeNecopinum@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
